### ISSUE TITLE
提示类组件不生效

### ISSUE THREAD

**Issue by Huboooo** [CharleeWa/vue3-vant-mobile#10]
提示类组件不生效，例如 Toast Notify，不知道是不是组件没引入

**Comment by CharleeWa** [comment]
按照 `Vant4` 文档的说明，像 `Toast`、`Notify` 这类组件都是函数组件，还包括 `Dialog` 、`ImagePreview `。这类组件在使用时，`unplugin-vue-components` 插件没有做样式自动引入的处理，所以需要我们手动引入样式。如下：

// Toast
import { Toast } from 'vant';
import 'vant/es/toast/style';

// Notify
import { Notify } from 'vant';
import 'vant/es/notify/style';

**Comment by Huboooo** [comment]
好的，稍后我试试😁
