### ISSUE TITLE
showConfirmDialog 导入报错

### ISSUE THREAD

**Issue by Codeniu** [CharleeWa/vue3-vant-mobile#12]
导入方式
import { showConfirmDialog } from 'vant'

导入报错
The requested module '/node_modules/.vite/deps/vant.js?v=c4b8af7e' does not provide an export named 'showConfirmDialog'

**Comment by CharleeWa** [comment]
> 

`Vant` 没有导出名为 ‘showConfirmDialog’ 的组件。可以参考 `Dialog` 的使用方式，参考链接：

https://vant-ui.github.io/vant/v4/#/zh-CN/dialog

注意：使用 `dialog` 组件，需要单独引用样式文件。

**Comment by CharleeWa** [comment]
@Codeniu  您好.

看了一下，确实存在这个问题。 查找Issues，得知是 `Vant` 官网的一个失误。详情：

https://github.com/youzan/vant/issues/10792

解决： 本项目所使用的 Vant 已更新至 `vant": "4.0.0-beta.0` 最新版本。

更新以后，可以直接使用 `showConfirmDialog ` API。

**Comment by Codeniu** [comment]
好的，我刚也看了官方的issue

**Comment by CharleeWa** [comment]
> 好的，我刚也看了官方的issue

嗯嗯
