### ISSUE TITLE
mock页面无法滚动

### ISSUE THREAD

**Issue by Silence-dream** [CharleeWa/vue3-vant-mobile#17]
因为长度不够
![image](https://user-images.githubusercontent.com/42824008/196388499-1f19f8a2-4e4b-492c-89dc-0253ad3be998.png)
移除高度限制即可正常
![image](https://user-images.githubusercontent.com/42824008/196388608-278f1e6b-8057-4028-81d1-55e3d3ccaeec.png)
在高度小的手机上会导致页面显示不全

**Comment by CharleeWa** [comment]
谢谢！
