### ISSUE TITLE
yarn build 出来的页面跟yarn dev的页面不一致

### ISSUE THREAD

**Issue by dafo374** [CharleeWa/vue3-vant-mobile#18]
新手提问，yarn build这个dist目录，打开后的页面是空白的是为啥？

**Comment by CharleeWa** [comment]
您好，我这边并未复现空白的问题。不过，我猜您是在打包构建后，本地直接双击运行 `dist/index.html` 文件，如果是这样，页面确实是空白的，仔细查看错误是由于资源路径导致的问题。对此，这个文章有更详细的描述：

https://juejin.cn/post/6844904064317128711。

如果只是想查看构建后的效果，我更建议使用如下命令：

> `yarn run preview`


这个命令会在本地启动一个静态 Web 服务器，将 dist 文件夹运行在 http://localhost:4173。

这样查看就方便了。

如果不是我所描述的问题，还请详细补充下信息，谢谢。

**Comment by dafo374** [comment]
谢谢解答。
额，那我想发布到服务器上部署，应该怎么发布？
如果不是用nginx ，而是用forever 在服务器上跑个，要怎么跑？

**Comment by CharleeWa** [comment]
抱歉，这个我没经验😅
