### ISSUE TITLE
Swipe 组件没有渐入动画效果

### ISSUE THREAD

**Issue by leo4developer** [CharleeWa/vue3-vant-mobile#23]
如主题,引入Swipe 组件后,van-swipe-item的切换,没有渐入动画效果

**Comment by CharleeWa** [comment]
您好，在 `app.less` 文件下 找到下面这句话删掉（一共两个）：

`transition: background-color 300ms`

这个设置和 Swipe 的 transition 冲突了，之前没有考虑到。

我后面也会更新上去。谢谢啦！

**Comment by CharleeWa** [comment]
已经更新，暂关闭Issues！如果有任何问题，可以继续在下面讨论。
