### ISSUE TITLE
你好，van-form van-field中修改placeholder不会热更新，不再van-form中会热更新，求助

### ISSUE THREAD

**Issue by cq112233** [CharleeWa/vue3-vant-mobile#26]
<van-form ref="form" @submit="submit">
        <van-field
          v-model="loginForm.phone"
          class="!h-140px"
          center
          label-class="label_width"
          placeholder="请输入原手机号(不会热更新)"
          label="+86"
          :rules="phoneRules"
          clearable
          type="tel"
        />
  </van-form>
 <van-field
          v-model="loginForm.phone"
          class="!h-140px"
          center
          label-class="label_width"
          placeholder="请输入原手机号(会热更新)"
          label="+86"
          :rules="phoneRules"
          clearable
          type="tel"
        />

**Comment by CharleeWa** [comment]
@cq112233 你好，感谢使用这个项目。

对于问题我掌握的信息不够多，是不是说 `van-field`在 `van-form`下的时候，改变 `placeholder `属性值时，页面元素没有及时变化？ 可否提供一下详细的描述和代码片段？谢谢！

**Comment by cq112233** [comment]
是的，van-field在 van-form下的时候，改变 placeholder 属性值时，页面元素没有及时变。
[https://files.catbox.moe/qss2lv.png](url)

**Comment by CharleeWa** [comment]
@cq112233 收到！（图片打不开！）

建议检查下 `placeholder` 是否设置为动态属性，例如：

`
// script
const val = ref('')

// template
<van-field :placeholder="val">
`
此外，我确认这不是项目本身的问题，可以查阅下vue 和 vant 官方文档。

**Comment by cq112233** [comment]
好的，谢谢
