### ISSUE TITLE
为什么在浏览器F12看element会很卡

### ISSUE THREAD

**Issue by Klayt11** [CharleeWa/vue3-vant-mobile#27]
浏览器F12看element会很卡，一点击元素那些标签就卡，时不时浏览器变未响应

**Comment by CharleeWa** [comment]
> 浏览器F12看element会很卡，一点击元素那些标签就卡，时不时浏览器变未响应

浏览器开的tab多吗？换个网站试试看。

**Comment by CharleeWa** [comment]
暂时关闭❤️
