### ISSUE TITLE
chrome51不支持/颜色异常

### ISSUE THREAD

**Issue by tkkcc** [CharleeWa/vue3-vant-mobile#28]
README中有写支持chrome51。

不修改直接build，页面上无内容。
修改legacy targets后build：
```patch
# vite.config.ts
       legacy({
-        targets: ['defaults', 'not IE 11'],
+        targets: ['chrome >= 51'],
       }),
```
页面有内容。点击暗黑模式，颜色异常：
![2023-01-13_21-19](https://user-images.githubusercontent.com/17373509/212329374-af0d4aa6-dcc4-4806-a8c8-4497e42192e9.png)

版本号：
![2023-01-13_21-18](https://user-images.githubusercontent.com/17373509/212329144-53fea58c-4bde-4a22-be3d-8fb7e45cd55e.png)

**Comment by CharleeWa** [comment]
@tkkcc 非常感谢，暗黑主题用到了 `color-scheme` css 属性，这个属性在chrome81以下不支持，建议升级chorme版本到81以上。此外，本地开发环境也建议使用chorme 81以上，这样bulid的问题估计也就解决了。

参考：[caniuse](https://caniuse.com/?search=color-scheme)
