### ISSUE TITLE
update postcss-px-to-viewport

### ISSUE THREAD

**Issue by CharleeWa** [CharleeWa/vue3-vant-mobile#3]
官网版本(v1.1.1)： [postcss-px-to-viewport](https://github.com/evrone/postcss-px-to-viewport)

warning： `postcss-px-to-viewport: postcss.plugin was deprecated.`  原来postcss v8以后不再支持原来的配置方式。

社区版本 三种选择：

- https://github.com/xian88888888/postcss-px-to-viewport-8-plugin
- https://github.com/philuo/postcss-px2vw
- https://github.com/Jonny-china/postcss-px-to-viewport

**Comment by wswmsword** [comment]
或许有第四个选择，postcss-px-to-viewport 的问题是不能限制视图的最大宽度，导致大屏大字的问题。

我最近写了个插件，[postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)，可以生成用来限制最大宽度的媒体查询，保持横屏和桌面端的可访问性，内部 postcss 同样依赖 8 版本，viewportWidth 支持传递函数动态生成视图宽度。CharleeWa，如果您觉得需要的话，欢迎试试我这个插件，或者我也可以提个 pr～

下面是我在这个项目里试用的截图：

<table>
	<tr>
		<td><img src="https://user-images.githubusercontent.com/26893092/221753495-d6a9e526-5cee-46ba-981f-906bfbe7e5b2.PNG" alt="移动端的展示效果" /></td>
		<td><img src="https://user-images.githubusercontent.com/26893092/221753449-562eb18c-badb-4c8f-b1ce-a2d594cf8018.PNG" alt="移动端横屏的展示效果" /></td>
	</tr>
	<tr>
		<td colspan="2"><img src="https://user-images.githubusercontent.com/26893092/221752560-02a68dba-5f3d-48f6-9a1b-04129babe712.png" alt="桌面端的展示效果" /></td>
	</tr>
</table>

**Comment by CharleeWa** [comment]
@wswmsword  太棒了! 欢迎提PR给我 ❤

**Comment by CharleeWa** [comment]
1985329d98e67cdccc3e1722c09e8d26b252be2a 后边有了新的调整，mark一下
