### ISSUE TITLE
如何关闭eslint

### ISSUE THREAD

**Issue by Devynlime** [CharleeWa/vue3-vant-mobile#35]
您好，本项目中如何关闭eslint的git监测呀，谢谢答复！

**Comment by CharleeWa** [comment]
@Devynlime 把 _`.husky / pre-commit`_ 脚本注释或者删掉。

**Comment by Devynlime** [comment]
好的谢谢，pre-commit文件没有格式后缀，没办法注释，我把它删掉试试

**Comment by CharleeWa** [comment]
> 好的谢谢，pre-commit文件没有格式后缀，没办法注释，我把它删掉试试

打开 _pre-commit_ 脚本文件，把这句话注释 ： `pnpm run lint`
