### ISSUE TITLE
pnpm build:dev 本地打包测试，dist下的index.html打开空白

### ISSUE THREAD

**Issue by Devynlime** [CharleeWa/vue3-vant-mobile#36]
pnpm build:dev 本地打包测试，dist下的index.html打开空白，
控制台报错：

Access to script at 'file:///D:/assets/index-4a56b301.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome-untrusted, https, edge.

![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/95b5bd2d-bf15-4c49-97f1-1cb40413773f)

**Comment by CharleeWa** [comment]
@Devynlime 你好，本地打开构建好的 `dist` 包会出现路径问题，打开 `index.html` 后，浏览器会根据系统路径加载其他资源，而不是服务器上的资源，浏览器有安全策略, 所以你本地打开就会出现上面的问题 。你需要把构建好的 `dist` 文件放到服务器上部署和访问，或者本地使用 `http-server` 这样的工具起一个服务预览程序。
