### ISSUE TITLE
格式化问题

### ISSUE THREAD

**Issue by startNewCount** [CharleeWa/vue3-vant-mobile#37]
遇到个奇怪的问题，为什么我新建了vue页面后，按CTRL+S保存后，会把页面格式化为另一种格式，不知如何修改。
保存(格式化)前：
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/124994421/c36e8f86-b535-423a-9e2e-693b693664a6)
保存(格式化)后：
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/124994421/f21304aa-71fa-48e6-8954-cca820cc4f3f)

**Comment by startNewCount** [comment]
第一行格式化后应该是<script setup lang="ts">，而不是 <template setup lang="ts">。不知为何会造成这样的情况

**Comment by startNewCount** [comment]
第一行格式化后应该是<script setup lang="ts">，而不是<template setup lang="ts"> 。不知为何会造成这样的情况

**Comment by CharleeWa** [comment]
@startNewCount 你好，我并没有复现闭合标签出现了错乱的问题：

```
<template ...> 
</script>  
```
可否提供一个 最小 repo地址，帮你看看。

**Comment by CharleeWa** [comment]
> 第一行格式化后应该是`<script setup lang="ts">`，而不是 `<template setup lang="ts">`。 不知为何会造成这样的情况

这个问题确实很奇怪，但是我认为不是 eslint 配置的 规则所导致的，你可以检查下你的编辑器的一些设置和扩展，为了不影响你业务开发，可以在 `.eslintrc` 里面注释掉这个规则集。

```
"extends": [
    // "@antfu"
],
```

**Comment by startNewCount** [comment]
## 我是通过pnpm plop生成的vue文件，如下
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/124994421/f2af76c2-1a1d-4563-8e72-9992cc79e33b)
## 当我按CTRL+S后，就会先执行一次格式化，然后就成了下面这样
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/124994421/30501672-40d8-4353-8304-b1651e155c96)

## 不知是否跟我的某些插件有关系

**Comment by startNewCount** [comment]
破案了，这个插件导致的
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/124994421/c6957435-871a-4ef3-ac96-7ac7c3094e8c)

**Comment by CharleeWa** [comment]
hahahah， 那就好 。
