### ISSUE TITLE
vite 的 http代理没有生效

### ISSUE THREAD

**Issue by Devynlime** [CharleeWa/vue3-vant-mobile#38]
配置了跨域地址http://localhost:9203/，但是依然请求前端的 http://localhost:3000
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/fde6f657-a1e6-49f0-b060-e9e01fa9bb39)
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/e7d47646-8fb6-41c4-91af-43d40a9f252f)

**Comment by CharleeWa** [comment]
@Devynlime 如果配置了代理，并且拦截规则也没问题的话，需要进一步排查问题，比如9203这个服务本身没有问题，通过postman测试下；还有API路径是不是正确。最后需要说明，如果你是在 `Request Header` 看到还是 3000这个地址，但是数据能拿到，这是因为 `proxy` 配置并不会改变你本地请求的 url（虽然从浏览器控制台的 Network 看，依旧是 http://127.0.0.1:3000/api/xxx) ，但是会在本地服务转发到 target 上 。有一张参照图：

![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/22477554/ecec6120-484a-40dc-bfdb-f02967449999)

**Comment by Devynlime** [comment]
> @Devynlime 如果配置了代理，并且拦截规则也没问题的话，需要进一步排查问题，比如9203这个服务本身没有问题，通过postman测试下；还有API路径是不是正确。最后需要说明，如果你是在 `Request Header` 看到还是 3000这个地址，但是数据能拿到，这是因为 `proxy` 配置并不会改变你本地请求的 url（虽然从浏览器控制台的 Network 看，依旧是 http://127.0.0.1:3000/api/xxx) ，但是会在本地服务转发到 target 上 。有一张参照图：
> 
> ![image](https://user-images.githubusercontent.com/22477554/249987788-ecec6120-484a-40dc-bfdb-f02967449999.png)

9203服务没有问题，直接通过axios写死路径是能够请求到的，但是现在是希望通过request封装来请求api，但是控制台看到路径任然是前端的3000端口，并报错

**Comment by CharleeWa** [comment]
@Devynlime 可以把报错信息和请求代码片段贴过来看看

**Comment by Devynlime** [comment]
> @Devynlime 可以把报错信息和请求代码片段贴过来看看

![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/f6f9b4ef-82ed-4a28-99bc-79d09a6543cf)
请求代码片段：
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/00cb9caa-7636-43b0-b65c-471b01e81e1a)
config：
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/0a9ab6db-6917-4861-a479-562bf0116a44)
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/a2fb6276-e0f6-407f-a630-1663c49442d5)
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/3c0c928a-d5e7-4d04-b7c7-b33f15695408)

**Comment by Devynlime** [comment]
> > @Devynlime 可以把报错信息和请求代码片段贴过来看看
> 
> ![image](https://user-images.githubusercontent.com/82365449/249995525-f6f9b4ef-82ed-4a28-99bc-79d09a6543cf.png) 请求代码片段： ![image](https://user-images.githubusercontent.com/82365449/249995642-00cb9caa-7636-43b0-b65c-471b01e81e1a.png) config： ![image](https://user-images.githubusercontent.com/82365449/249995703-0a9ab6db-6917-4861-a479-562bf0116a44.png) ![image](https://user-images.githubusercontent.com/82365449/249995725-a2fb6276-e0f6-407f-a630-1663c49442d5.png) ![image](https://user-images.githubusercontent.com/82365449/249995856-3c0c928a-d5e7-4d04-b7c7-b33f15695408.png)
附：启动参数：
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/ff336af1-8f1c-47e5-8698-eef32dfdbfe0)

**Comment by Devynlime** [comment]
您好，目前我有了新进展，
修改了路径重写replace后，能接受到数据，后台也看到了访问，但是：
* 页面控制台的路径地址是不打印具体后台地址的，请问这是正常的吗；
* 此外还有一些意外的报错，例如其中返回data格式包含有ac属性，但是控制台输出未找到对应属性；
贴上相应的一些截图（我添加了rewrite）：
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/60ca4706-3a4a-41cc-9992-2478de8877c5)
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/5d2fb218-144c-4f01-9497-a4b8276ad233)
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/bb638a17-8576-4b9e-a338-cab764c37a17)

**Comment by Devynlime** [comment]
报错对应代码，
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/b93c3b42-9371-4cae-a881-5736f143731c)
可能是封装之后的request直接将结果集对象返回到then接收了，所以删掉一层`.data`得以解决问题，十分谢谢！

**Comment by CharleeWa** [comment]
> 您好，目前我有了新进展， 修改了路径重写replace后，能接受到数据，后台也看到了访问，但是：
> 
> * 页面控制台的路径地址是不打印具体后台地址的，请问这是正常的吗；
> * 此外还有一些意外的报错，例如其中返回data格式包含有ac属性，但是控制台输出未找到对应属性；
>   贴上相应的一些截图（我添加了rewrite）：
>   ![image](https://user-images.githubusercontent.com/82365449/249998130-60ca4706-3a4a-41cc-9992-2478de8877c5.png)
>   ![image](https://user-images.githubusercontent.com/82365449/249998161-5d2fb218-144c-4f01-9497-a4b8276ad233.png)
>   ![image](https://user-images.githubusercontent.com/82365449/249998203-bb638a17-8576-4b9e-a338-cab764c37a17.png)

这是正常的，解决就好。
