### ISSUE TITLE
使用ios混合开发时 wkwebview加载dist导致白屏无法加载

### ISSUE THREAD

**Issue by camenling** [CharleeWa/vue3-vant-mobile#39]
使用ios swift wkwebview加载dist, 无报错, 但是白屏无法加载

**Comment by CharleeWa** [comment]
@camenling 你好，我这边混合开发经验是需要先部署这个应用，然后用webview去加载部署后的地址进行渲染。不能直接加载 `dist` 这个文件夹。

**Comment by CharleeWa** [comment]
暂时关闭，有问题再反馈哈
