### ISSUE TITLE
关于mock请求规则的疑惑

### ISSUE THREAD

**Issue by Devynlime** [CharleeWa/vue3-vant-mobile#40]
作者您好，这里关于mock的配置方式，我有一些不明白和不理解的地方还想学习一下，请问这里的mock/modules/prose.js中的这种导出方式，是基于什么规则实现的mock请求拦截呀，我不是很清楚其中的运行机制，此前我也去查看了下mockjs的官方文档，没有头绪，希望学习一下作者对于此中的封装思想是如何的？希望能够得到恢复，谢谢！！
mock/modules/prose.js:
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/ed1046f4-bef2-4104-a2fd-2955603ccce8)
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/0db72965-051c-4c89-a84b-82435f04488b)
mock/index.js:
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/76043caa-1380-49a5-a5ab-a7b59181d23d)
api中对于配置好的mock的请求：
![image](https://github.com/CharleeWa/vue3-vant-mobile/assets/82365449/754a659c-eded-470f-8e8c-89c9acd7235a)

**Comment by Devynlime** [comment]
上面的提问中有错别字，“恢复”应为“回复”！

**Comment by CharleeWa** [comment]
@Devynlime 感谢你提出这个问题。其实所有的 `mock` 本质上都是一样的，就是拦截客户端请求，模拟服务器响应，只不过技术框架不同，实现方式也有所不同，我想这个是让你比较有困惑的地方。就拿这个项目来说，我实现 `mock` 的方式，是写了一个中间件来处理客户端请求，具体来讲，我写了一个 `vite` 插件，可以在项目根目录 `build` 文件夹下看到这些原始脚本文件，然后在 `vite.config.ts` 下面的 `plugins` 进行注册。如下：

```
mock({
  watch: true,
  mockUrlList: [/api/],
  cwd: process.cwd(),
  enable: true
}),
```

这样，只要 `vite` 开发服务器启动，就会执行这些插件，如果插件监听到客户端的请求，比如 `/api/project/prose` , 就会被我的中间件所拦截，然后处理下面的响应。我截取几个代码片段，你理解下。这些代码都可以在 `build/mock/createMockServer.js`找到。

```
// 1 、初始化要监听的文件，这里是监听Mock文件夹
function initWatchMockFiles(paths) {
  const absPagesGlobPath = winPath(join('./mock', '**/*.[jt]s'))
  watcher = chokidar.watch([...['./mock'], absPagesGlobPath], {
    ignoreInitial: true,
  })
  …………
})
```

```
// 2、导出给Vite插件的主函数
module.exports = function (opts) {
  …………
  const paths = [absMockPath]
 // 如果启用mock，执行下面的逻辑
  if (options.enable) {
    initMock(options)
    if (options.watch)
     // 初始化上面的函数
      initWatchMockFiles(paths)
  }
}
```

```
// 3、中间件逻辑，主要功能是路由处理器
const middleware = async (req, res, next) => {
// 匹配到路由 ，返回数据给客户端
 const matchMock = getMatchMock(req.url)
…………
})
 middlewares.use(middleware)
```

总结来说，只要当你的应用在浏览器中运行并发起一个HTTP请求时，这个请求会被发送到Vite的开发服务器，然后进一步被 mock中间件拦截，一旦被拦截，就会根据预设规则生成一个响应，大概来讲就是这么回事。我没有用到第三方mock集成的插件，但原理都是差不多的，并且这个实现比较灵活，数据规则自己决定。

以上，希望能帮助到你。

**Comment by Devynlime** [comment]
谢谢！！明白了！
