### ISSUE TITLE
pnpm dev iOS safari 浏览器访问ip:3000会显示空白页

### ISSUE THREAD

**Issue by lvchangye** [CharleeWa/vue3-vant-mobile#41]
pnpm dev开启本地服务
iOS safari 浏览器访问ip:3000会显示空白页
PC和安卓手机没问题

**Comment by CharleeWa** [comment]
@lvchangye 嗨，我这边没有复测出空白页的问题，请确保电脑和手机连接的是同一个Wi-Fi 网络，如果问题仍然存在，请提供下ios 和 safair 的版本信息。你也可以开启 VConsole, 检查输出面板有没有错误信息。

**Comment by CharleeWa** [comment]
暂时关闭，还有问题请留言。
