### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by liyang1987jay** [CharleeWa/vue3-vant-mobile#43]
可以结合uniapp吗？否则app怎么打包啊

**Comment by CharleeWa** [comment]
@liyang1987jay  你好，这个项目不适用于 uniapp，因为不可能完整地运行，需要配置和修改不少东西。我建议是使用 uniapp 自己的生态搭建起一个项目，再把这个项目当中你喜欢的东西拿过去。

**Comment by liyang1987jay** [comment]
好的
