### ISSUE TITLE
这个模板是不是没有提供样式格式化的功能

### ISSUE THREAD

**Issue by 60late** [CharleeWa/vue3-vant-mobile#45]
看了package.json里面没有配置prettier，虽然用了antfu的eslint-config，但是也可以配置stylelint的自动修复吧？

**Comment by CharleeWa** [comment]
@60late 你好，是的。这一点当时确实没有考虑在内，后边我想使用 `unocss`，不再编写css，所以现在集成的意义可能不大了。谢谢你的建议！

**Comment by 60late** [comment]
我自己尝试了一下，就算集成了stylelint也是问题重重，并且stylelint最新版已经要废弃掉自动修复的功能了
可能antfu这个eslint-config确实只适合用原子化的样式方案吧
期待后续更新~

**Comment by CharleeWa** [comment]
@60late 已经更新 92564364a58252e92726e0dc0ddf048407072a7e
