### ISSUE TITLE
keepalive 什么时候加一下哈

### ISSUE THREAD

**Issue by tlerbao** [CharleeWa/vue3-vant-mobile#65]
keepalive 什么时候加一下哈

**Comment by CharleeWa** [comment]
在线等一个PR 😊

**Comment by CharleeWa** [comment]
`<keep-alive>` 和 目前基于文件[路由布局](https://github.com/JohnCampionJr/vite-plugin-vue-layouts)系统存在冲突，导致组件缓存失效，应该是多级路由引起的问题。我正在考虑移除[文件路由](https://github.com/posva/unplugin-vue-router)以及布局系统，改为传统路由设计。这是一个非常典型的 为了DX而影响功能性的一个问题。

> DX  > 文件路由  >  文件路由布局  > keep-alive 失效/等等

如果是多级路由导致的组件缓存失效，目前的方案是平铺路由，可以参考这个[issue](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/74)，但是我不想在模版当中用这个方法解决这个问题，因为可能还会有其它潜在问题，我可能更愿意移除掉这些代码。请跟踪后续更新计划。

**Comment by tlerbao** [comment]
@CharleeWa 不能共存吗？感觉直接移除文件路由和布局系统，损失有点大啊，要手写一堆路由配置
