### ISSUE TITLE
请问下作者为什么没有考虑tailwindcss呢？tailwindcss受众更广，更易使用啊

### ISSUE THREAD

**Issue by smartdapan** [CharleeWa/vue3-vant-mobile#72]
请问下作者为什么没有考虑tailwindcss呢？tailwindcss受众更广，更易使用啊

**Comment by CharleeWa** [comment]
有几个综合原因。首先要说的是，即便是使用了 unocss, 它也是在使用原子化 CSS，并没有脱离目标 - 让写 CSS 更方便。可以看下 [ 重新构想原子化 CSS ](https://antfu.me/posts/reimagine-atomic-css-zh)这篇文章，它是一个引擎，不是某一个 CSS 框架，也就是说更灵活一些。其次，unocss 拥有更多[官方插件](https://unocss.dev/presets/)，相比 tailwindcss 的 [官方插件](https://tailwindcss.com/docs/plugins#official-plugins)，它太少了！但不可否认，tailwindcss 的社区基础更好。还有一些现实原因，也是我选择 unocss 的主要原因。这个移动端项目采用 vw/vh 单位在各个屏幕上做到适配，是使用了 `postcss-px-to-viewport` 插件把 px 单位转换为 vw 单位；除了写普通的 CSS，或者像 Less、Sass 这种 CSS 预处理器，如果想集成原子化 CSS，就需要考虑集成问题。因为所有的原子化 CSS 方案都采用了 rem 作为 CSS 单位，那么 unocss 有一个[rem-to-px](https://unocss.dev/presets/rem-to-px)的预设，可以很好解决我们遇到的问题。它在我们项目构建阶段，做了一件事：rem -> px -> vw。而 tailwindcss 是没有这样的官方预设的，虽然这样的需求被很多人所需要，可以看看这个[issue](https://github.com/tailwindlabs/tailwindcss/issues/1232)。综上，我选择了 unocss。

**Comment by smartdapan** [comment]
谢谢作者如此细致的回答，由于我是一名后端程序员，对前端如此之多的技术栈实在有点应接不暇；找这种整合好的开箱即用的template主要就是想尽量减少在配置和技术栈上花更多的时间精力，感谢作者的分享

**Comment by CharleeWa** [comment]
谢谢支持，有任何问题我们再交流
